server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://register1:8000/eureka/,http://register2:8000/eureka/
  instance:
    prefer-ip-address: true
