apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: web
          image: [registry address]
          ports:
            - containerPort: 2222
          env:
            - name: APP_OPTS
              value: "
           --eureka.instance.prefer-ip-address=true
                     --eureka.client.serviceUrl.defaultZone=http://eureka-0:8000/eureka/,http://eureka-1:8000/eureka/,http://eureka-2:8000/eureka/"
