apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: web
          image: registry-vpc.cn-hangzhou.aliyuncs.com/bestpractise/gateway
          ports:
            - containerPort: 8080
          env:
            - name: APP_OPTS
              value: "
           --eureka.instance.prefer-ip-address=true
                     --eureka.client.serviceUrl.defaultZone=http://eureka-0:8000/eureka/,http://eureka-1:8000/eureka/,http://eureka-2:8000/eureka/"
