spring:
  application:
    name: spring-cloud-producer
server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://register1:8000/eureka/,http://register2:8000/eureka/
  instance:
      prefer-ip-address: true