spring:
  application:
    name: spring-cloud-consumer
server:
  port: 2222
eureka:
  client:
    serviceUrl:
      defaultZone: http://register1:8000/eureka/,http://register2:8000/eureka/
  instance:
    prefer-ip-address: true