---
spring:
  application:
    name: spring-cloud-eureka
  profiles: register1
server:
  port: 8000
eureka:
  instance:
    hostname: register1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://register2:8000/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
      enable-self-preservation: false
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: register2
server:
  port: 8000
eureka:
  instance:
    hostname: register2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://register1:8000/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false